#include "Core.hpp"
#include "FFlagDumper.hpp"
#include <conio.h>
#include <fstream>
#include <filesystem>
#include <cstdint>
#include <iostream>
#include <algorithm>
#include <map>
#include "Stages/TaskScheduler.hpp"
#include "Stages/FakeDataModel.hpp"
#include "Stages/Instance.hpp"
#include "Stages/Script.hpp"
#include "Stages/DataModel.hpp"
#include "Stages/Humanoid.hpp"
#include "Stages/Workspace.hpp"

static BOOL WINAPI CtrlHandler(DWORD t) {
    if (t == CTRL_C_EVENT || t == CTRL_BREAK_EVENT) {
        printf("\n[!] Interrupted\n");
        return TRUE;
    }
    return FALSE;
}

static bool IsRunningAsAdmin() {
    BOOL r = FALSE;
    PSID g = nullptr;
    SID_IDENTIFIER_AUTHORITY auth = SECURITY_NT_AUTHORITY;
    if (AllocateAndInitializeSid(&auth, 2, SECURITY_BUILTIN_DOMAIN_RID,
        DOMAIN_ALIAS_RID_ADMINS, 0, 0, 0, 0, 0, 0, &g)) {
        CheckTokenMembership(nullptr, g, &r);
        FreeSid(g);
    }
    return r == TRUE;
}

static DWORD PIDByName(const std::string& name) {
    std::string lo = name;
    for (auto& c : lo) c = tolower(c);
    HANDLE snap = CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0);
    if (snap == INVALID_HANDLE_VALUE) return 0;
    PROCESSENTRY32W pe{ sizeof(pe) };
    DWORD found = 0;
    if (Process32FirstW(snap, &pe)) {
        do {
            std::wstring w(pe.szExeFile);
            std::string n(w.begin(), w.end());
            for (auto& c : n) c = tolower(c);
            if (n == lo || n == lo + ".exe") {
                found = pe.th32ProcessID;
                break;
            }
        } while (Process32NextW(snap, &pe));
    }
    CloseHandle(snap);
    return found;
}


static void GenerateCombinedHeader(
    const std::string& path,
    uintptr_t taskSchedulerRVA,
    const std::vector<StructField>& fields,
    uintptr_t fakeDataModelRVA,
    std::optional<uint32_t> fakeToRealOffset,
    std::optional<uint32_t> jobNameOffset,
    std::optional<uint32_t> maxFpsOffset,
    const std::vector<FFlagEntry>& flags,
    const FFlagOffsets& fflagOffsets,
    uintptr_t moduleBase,
    const InstanceOffsets& instOffsets,
    const ScriptOffsets& scriptOffsets,
    const DataModelOffsets& dataModelOffsets,
    const HumanoidOffsets& humanoidOffsets,
    const WorkspaceOffsets& workspaceOffsets)
{
    std::ofstream h(path);
    if (!h) { LOG_ERR("Cannot write combined header"); return; }

    uint32_t jobStart = 0, jobEnd = 0;
    std::map<uint32_t, uint32_t> containerPairs;
    for (const auto& f : fields) {
        if (f.isContainer && f.containerBegin && f.containerEnd)
            containerPairs[f.containerBegin] = f.containerEnd;
    }
    if (containerPairs.count(0xC8) && containerPairs[0xC8] == 0xD0) {
        jobStart = 0xC8; jobEnd = 0xD0;
    }
    else {
        for (const auto& [begin, end] : containerPairs) {
            if (end - begin == 8) {
                bool hasStride = false;
                for (const auto& f : fields)
                    if (f.offset >= begin && f.offset < end && f.stride != 0) { hasStride = true; break; }
                if (hasStride) { jobStart = begin; jobEnd = end; break; }
            }
        }
    }

    h << "#ifndef OFFSETS_AND_FFLAGS_H\n";
    h << "#define OFFSETS_AND_FFLAGS_H\n\n";
    h << "#include <cstdint>\n";
    h << "#include <string>\n\n";
    h << "//  Roblox Offsets & FFlags  (auto-generated by RobloxDumper)\n";
    h << "//  by bosssohio164\n";

    h << "namespace Offsets {\n";

    h << "    namespace TaskScheduler {\n";
    h << "        static constexpr uintptr_t TaskSchedulerPointer = 0x" << std::hex << taskSchedulerRVA << ";\n";
    if (jobStart && jobEnd) {
        h << "        static constexpr uint32_t JobStart = 0x" << std::hex << jobStart << ";\n";
        h << "        static constexpr uint32_t JobEnd   = 0x" << std::hex << jobEnd << ";\n";
    }
    if (jobNameOffset) h << "        static constexpr uint32_t JobNameOffset = 0x" << std::hex << *jobNameOffset << ";\n";
    if (maxFpsOffset)  h << "        static constexpr uint32_t MaxFpsOffset = 0x" << std::hex << *maxFpsOffset << ";\n";
    h << "    }\n\n";

    h << "    namespace FakeDataModel {\n";
    h << "        static constexpr uintptr_t FakeDataModelPointer = 0x" << std::hex << fakeDataModelRVA << ";\n";
    if (fakeToRealOffset) h << "        static constexpr uint32_t FakeToRealDataModel = 0x" << std::hex << *fakeToRealOffset << ";\n";
    h << "    }\n\n";

    h << "    namespace Instance {\n";
    if (instOffsets.Valid) {
        h << "        static constexpr uint32_t ChildrenStart = 0x" << std::hex << instOffsets.ChildrenStart << ";\n";
        h << "        static constexpr uint32_t ChildrenEnd   = 0x" << std::hex << instOffsets.ChildrenEnd << ";\n";
        if (instOffsets.Name)           h << "        static constexpr uint32_t Name     = 0x" << std::hex << instOffsets.Name << ";\n";
        if (instOffsets.Parent)         h << "        static constexpr uint32_t Parent   = 0x" << std::hex << instOffsets.Parent << ";\n";
        if (instOffsets.ClassDescriptor) h << "        static constexpr uint32_t ClassDescriptor = 0x" << std::hex << instOffsets.ClassDescriptor << ";\n";
        if (instOffsets.ClassName)      h << "        static constexpr uint32_t ClassName = 0x" << std::hex << instOffsets.ClassName << ";\n";
    }
    h << "    }\n\n";

    if (scriptOffsets.Valid) {
        h << "    namespace ModuleScript {\n";
        h << "        static constexpr uint32_t Bytecode = 0x" << std::hex << scriptOffsets.ModuleScriptBytecode << ";\n";
        h << "        static constexpr uint32_t Hash = 0x" << std::hex << scriptOffsets.ModuleScriptHash << ";\n";
        h << "    }\n\n";

        h << "    namespace LocalScript {\n";
        h << "        static constexpr uint32_t Bytecode = 0x" << std::hex << scriptOffsets.LocalScriptBytecode << ";\n";
        h << "        static constexpr uint32_t Hash = 0x" << std::hex << scriptOffsets.LocalScriptHash << ";\n";
        h << "    }\n\n";

        h << "    namespace ByteCode {\n";
        h << "        static constexpr uint32_t Pointer = 0x" << std::hex << scriptOffsets.ByteCodePointer << ";\n";
        h << "        static constexpr uint32_t Size = 0x" << std::hex << scriptOffsets.ByteCodeSize << ";\n";
        h << "    }\n\n";
    }

    if (dataModelOffsets.Valid) {
        h << "    namespace DataModel {\n";
        if (dataModelOffsets.GameLoaded)   h << "        static constexpr uint32_t GameLoaded = 0x" << std::hex << dataModelOffsets.GameLoaded << ";\n";
        if (dataModelOffsets.JobId)        h << "        static constexpr uint32_t JobId = 0x" << std::hex << dataModelOffsets.JobId << ";\n";
        if (dataModelOffsets.ServerIP)     h << "        static constexpr uint32_t ServerIP = 0x" << std::hex << dataModelOffsets.ServerIP << ";\n";
        h << "    }\n\n";
    }

    if (humanoidOffsets.Valid) {
        h << "    namespace Humanoid {\n";
        if (humanoidOffsets.Health)           h << "        static constexpr uint32_t Health = 0x" << std::hex << humanoidOffsets.Health << ";\n";
        if (humanoidOffsets.MaxHealth)        h << "        static constexpr uint32_t MaxHealth = 0x" << std::hex << humanoidOffsets.MaxHealth << ";\n";
        if (humanoidOffsets.WalkSpeed)        h << "        static constexpr uint32_t WalkSpeed = 0x" << std::hex << humanoidOffsets.WalkSpeed << ";\n";
        if (humanoidOffsets.JumpPower)        h << "        static constexpr uint32_t JumpPower = 0x" << std::hex << humanoidOffsets.JumpPower << ";\n";
        if (humanoidOffsets.JumpHeight)       h << "        static constexpr uint32_t JumpHeight = 0x" << std::hex << humanoidOffsets.JumpHeight << ";\n";
        if (humanoidOffsets.HipHeight)        h << "        static constexpr uint32_t HipHeight = 0x" << std::hex << humanoidOffsets.HipHeight << ";\n";
        if (humanoidOffsets.MaxSlopeAngle)    h << "        static constexpr uint32_t MaxSlopeAngle = 0x" << std::hex << humanoidOffsets.MaxSlopeAngle << ";\n";
        if (humanoidOffsets.WalkTimer)        h << "        static constexpr uint32_t WalkTimer = 0x" << std::hex << humanoidOffsets.WalkTimer << ";\n";
        if (humanoidOffsets.HealthDisplayDistance) h << "        static constexpr uint32_t HealthDisplayDistance = 0x" << std::hex << humanoidOffsets.HealthDisplayDistance << ";\n";
        if (humanoidOffsets.AutoJumpEnabled)  h << "        static constexpr uint32_t AutoJumpEnabled = 0x" << std::hex << humanoidOffsets.AutoJumpEnabled << ";\n";
        if (humanoidOffsets.AutoRotate)       h << "        static constexpr uint32_t AutoRotate = 0x" << std::hex << humanoidOffsets.AutoRotate << ";\n";
        if (humanoidOffsets.Sit)              h << "        static constexpr uint32_t Sit = 0x" << std::hex << humanoidOffsets.Sit << ";\n";
        if (humanoidOffsets.BreakJointsOnDeath) h << "        static constexpr uint32_t BreakJointsOnDeath = 0x" << std::hex << humanoidOffsets.BreakJointsOnDeath << ";\n";
        if (humanoidOffsets.NameOcclusion)    h << "        static constexpr uint32_t NameOcclusion = 0x" << std::hex << humanoidOffsets.NameOcclusion << ";\n";
        if (humanoidOffsets.PlatformStand)    h << "        static constexpr uint32_t PlatformStand = 0x" << std::hex << humanoidOffsets.PlatformStand << ";\n";
        if (humanoidOffsets.RequiresNeck)     h << "        static constexpr uint32_t RequiresNeck = 0x" << std::hex << humanoidOffsets.RequiresNeck << ";\n";
        if (humanoidOffsets.UseJumpPower)     h << "        static constexpr uint32_t UseJumpPower = 0x" << std::hex << humanoidOffsets.UseJumpPower << ";\n";
        if (humanoidOffsets.RigType)          h << "        static constexpr uint32_t RigType = 0x" << std::hex << humanoidOffsets.RigType << ";\n";
        if (humanoidOffsets.HumanoidState)    h << "        static constexpr uint32_t HumanoidState = 0x" << std::hex << humanoidOffsets.HumanoidState << ";\n";
        if (humanoidOffsets.CameraOffset)     h << "        static constexpr uint32_t CameraOffset = 0x" << std::hex << humanoidOffsets.CameraOffset << ";\n";
        if (humanoidOffsets.MoveDirection)    h << "        static constexpr uint32_t MoveDirection = 0x" << std::hex << humanoidOffsets.MoveDirection << ";\n";
        if (humanoidOffsets.HumanoidRootPart) h << "        static constexpr uint32_t HumanoidRootPart = 0x" << std::hex << humanoidOffsets.HumanoidRootPart << ";\n";
        if (humanoidOffsets.SeatPart)         h << "        static constexpr uint32_t SeatPart = 0x" << std::hex << humanoidOffsets.SeatPart << ";\n";
        if (humanoidOffsets.DisplayName)      h << "        static constexpr uint32_t DisplayName = 0x" << std::hex << humanoidOffsets.DisplayName << ";\n";
        h << "    }\n\n";
    }

    if (workspaceOffsets.Valid) {
        h << "    namespace Workspace {\n";
        if (workspaceOffsets.CurrentCamera)       h << "        static constexpr uint32_t CurrentCamera = 0x" << std::hex << workspaceOffsets.CurrentCamera << ";\n";
        if (workspaceOffsets.World)               h << "        static constexpr uint32_t World = 0x" << std::hex << workspaceOffsets.World << ";\n";
        if (workspaceOffsets.DistributedGameTime) h << "        static constexpr uint32_t DistributedGameTime = 0x" << std::hex << workspaceOffsets.DistributedGameTime << ";\n";
        h << "    }\n\n";
    }

    h << "} // namespace Offsets\n\n";

    h << "namespace FFlags {\n";
    if (fflagOffsets.FFlagList != 0) {
        h << "    namespace Offsets {\n";
        h << "        static constexpr uintptr_t FFlagListOffset = 0x" << std::uppercase << std::hex << fflagOffsets.FFlagList << ";\n";
        h << "        static constexpr uintptr_t ValueGetSetOffset = 0x" << std::hex << fflagOffsets.ValueGetSet << ";\n";
        h << "        static constexpr uintptr_t FlagToValueOffset = 0x" << std::hex << fflagOffsets.FlagToValue << ";\n";
        h << "    }\n\n";
    }

    h << "    namespace Values {\n";
    h << "        static constexpr size_t Count = " << flags.size() << ";\n\n";
    h << "        // Individual FFlag offsets (RVA from module base)\n";
    for (const auto& f : flags) {
        uintptr_t offset = f.address - moduleBase;
        std::string varName = ToValidIdentifier(f.name);
        h << "        static constexpr uintptr_t " << varName << " = 0x" << std::uppercase << std::hex << offset << ";\n";
    }
    h << "    }\n";
    h << "} // namespace FFlags\n\n";

    h << "#endif // OFFSETS_AND_FFLAGS_H\n";
    h.close();
    LOG_OK("Combined header written to " + path);
}

int main() {
    SetConsoleOutputCP(CP_UTF8);
    SetConsoleCtrlHandler(CtrlHandler, TRUE);
    InitNtFunctions();

    g_ForceDecrypt = true;
    g_SuspendProcess = true;

    std::string processName = "RobloxPlayerBeta.exe";
    LOG_INFO("Targeting process: " + processName);

    if (!IsRunningAsAdmin()) LOG_WARN("Not admin -> decryption may fail");

    DWORD pid = PIDByName(processName);
    if (!pid) { LOG_ERR("Process not found"); return 1; }
    LOG_OK("PID: " + std::to_string(pid));

    HANDLE hProc = OpenProcess(
        PROCESS_VM_READ | PROCESS_VM_OPERATION | PROCESS_QUERY_INFORMATION,
        FALSE, pid);
    if (!hProc) { LOG_ERR("OpenProcess failed"); return 1; }
    LOG_OK("Process opened");

    uintptr_t modBase = 0, modSize = 0;
    std::string modName;
    HMODULE m{};
    DWORD need = 0;
    if (!EnumProcessModules(hProc, &m, sizeof(m), &need)) { LOG_ERR("EnumProcessModules failed"); return 1; }
    char path[MAX_PATH];
    GetModuleFileNameExA(hProc, m, path, sizeof(path));
    modName = std::filesystem::path(path).filename().string();
    MODULEINFO mi{};
    if (!GetModuleInformation(hProc, m, &mi, sizeof(mi))) { LOG_ERR("GetModuleInformation failed"); return 1; }
    modBase = (uintptr_t)mi.lpBaseOfDll;
    modSize = mi.SizeOfImage;
    LOG_INFO("Module: " + modName + " @ " + ToHex(modBase) + "  " + std::to_string(modSize / 1024) + " KB");

    auto pe = ParsePE(hProc, modBase);
    if (!pe) { LOG_ERR("PE parsing failed"); return 1; }

    const SectionInfo* rdata = nullptr;
    const SectionInfo* data = nullptr;
    for (const auto& s : pe->sections) {
        if (strcmp(s.name, ".rdata") == 0) rdata = &s;
        if (strcmp(s.name, ".data") == 0) data = &s;
    }
    if (!rdata || !data) { LOG_ERR("missing .rdata or .data, have u tried to load bullshot?"); return 1; }
    std::vector<uint8_t> rdataBuf = ReadSection(hProc, *pe, *rdata, g_ForceDecrypt);
    std::vector<uint8_t> dataBuf = ReadSection(hProc, *pe, *data, g_ForceDecrypt);

    LOG_INFO("phase 1: taskscheduler (first)");
    std::string needleStr = "TaskScheduler::Job: ";
    std::vector<uint8_t> needle(needleStr.begin(), needleStr.end());
    std::vector<StringHit> hits = DiscoverString(rdataBuf, modBase + rdata->rva, needle);
    if (hits.empty()) hits = DiscoverString(dataBuf, modBase + data->rva, needle);
    if (hits.empty()) { LOG_ERR("taskScheduler string not found in rdata"); return 1; }
    uintptr_t stringVA = hits[0].va;
    LOG_OK("Found string at VA " + ToHex(stringVA));

    const SectionInfo* tsec = nullptr;
    for (const auto& s : pe->sections)
        if (strcmp(s.name, ".text") == 0) tsec = &s;
    if (!tsec) { LOG_ERR("No .text section"); return 1; }
    std::vector<uint8_t> textBuf = ReadTextGhost(hProc, *pe, *tsec);

    StringHit sh; sh.va = stringVA; sh.encoding = "Narrow";
    std::vector<StringHit> stringHits = { sh };
    auto singletons = ResolveSingleton(textBuf, modBase + tsec->rva, modBase, *pe, stringHits);
    if (singletons.empty()) { LOG_ERR("no singleton found for TaskScheduler, gl"); return 1; }
    uintptr_t taskSchedulerRVA = singletons[0].targetRVA;
    LOG_OK("taskScheduler pointer: RVA 0x" + ToHex(taskSchedulerRVA, 8));

    uintptr_t taskSchedulerPtr = modBase + taskSchedulerRVA;
    uintptr_t taskSchedulerObj = 0;
    SIZE_T got;
    if (!SafeRead(hProc, taskSchedulerPtr, &taskSchedulerObj, 8, got) || got != 8 || taskSchedulerObj == 0) {
        LOG_ERR("failed to read TaskScheduler object, just talk to ass"); return 1;
    }
    LOG_OK("taskScheduler object at " + ToHex(taskSchedulerObj));

    auto fields = AnalyzeStructFields(textBuf, modBase + tsec->rva, modBase, singletons[0]);
    LOG_OK("found " + std::to_string(fields.size()) + " fields, great");

    std::optional<uint32_t> jobNameOffset;
    std::map<uint32_t, uint32_t> containerPairs;
    for (const auto& f : fields)
        if (f.isContainer && f.containerBegin && f.containerEnd)
            containerPairs[f.containerBegin] = f.containerEnd;
    uint32_t jobStartOffset = 0xC8;
    if (containerPairs.count(0xC8) && containerPairs[0xC8] == 0xD0)
        jobStartOffset = 0xC8;
    else if (!containerPairs.empty())
        jobStartOffset = containerPairs.begin()->first;
    jobNameOffset = FindJobNameOffset(hProc, taskSchedulerObj, jobStartOffset);
    auto maxFpsOffset = FindMaxFpsOffset(hProc, taskSchedulerObj);

    LOG_INFO("phase 2: fakedatamodel!!!!11");
    auto rttiRes = FindRTTI(hProc, *pe, rdataBuf, dataBuf, ".?AVDataModel@RBX@@");
    if (!rttiRes) { LOG_ERR("fakeDataModel RTTI not found in .data!"); return 1; }
    uintptr_t fakeDataModelRVA = rttiRes->singletonRVA;
    LOG_OK("FakeDataModel pointer: RVA 0x" + ToHex(fakeDataModelRVA, 8));

    uintptr_t objectAddr = 0;
    std::optional<uint32_t> fakeToRealOffset;

    uintptr_t singletonPtr = modBase + fakeDataModelRVA;
    if (SafeRead(hProc, singletonPtr, &objectAddr, 8, got) && got == 8 && objectAddr) {
        LOG_OK("yay, FakeDataModel object at " + ToHex(objectAddr));
        auto off = FindOffsetInObjectByRTTI(hProc, *pe, rdataBuf, dataBuf, objectAddr, "DataModel");
        if (off) {
            fakeToRealOffset = *off;
            LOG_OK("FakeToRealDataModel offset: 0x" + ToHex(*off, 4));
        }
    }
    else {
        LOG_ERR("Failed to read FakeDataModel object");
    }

    uintptr_t dataModelObj = 0;
    if (fakeToRealOffset.has_value() && objectAddr != 0) {
        if (SafeRead(hProc, objectAddr + *fakeToRealOffset, &dataModelObj, 8, got) && got == 8 && dataModelObj != 0) {
            LOG_OK("yay, Real DataModel object at " + ToHex(dataModelObj));
        }
        else {
            LOG_ERR("Could not read real DataModel from fake");
        }
    }
    else {
        LOG_WARN("No fake-to-real offset, cannot get real DataModel");
    }

    LOG_INFO("phase 3: longest fflags scanner scary boo");
    auto fflagOffsets = FindFFlagOffsets(hProc, modBase);
    std::vector<FFlagEntry> flags;
    if (fflagOffsets) {
        flags = DumpFFlagsWithOffsets(hProc, modBase, *fflagOffsets);
        WriteFFlags(flags, "fflags.txt", "fflags.json");
    }
    else {
        LOG_ERR("fflags offsets not found :(, we skip");

        LOG_INFO("phase 4: most important!1!111 instance");
        InstanceOffsets instanceOffsets;

        if (dataModelObj != 0) {
            instanceOffsets = FindInstanceOffsets(hProc, dataModelObj, rdataBuf, dataBuf);

            if (instanceOffsets.Valid) {
                LOG_OK("ChildrenStart: 0x" + ToHex(instanceOffsets.ChildrenStart));
                LOG_OK("ChildrenEnd:   0x" + ToHex(instanceOffsets.ChildrenEnd));
                LOG_OK("Name:          0x" + ToHex(instanceOffsets.Name));
                LOG_OK("Parent:        0x" + ToHex(instanceOffsets.Parent));
                LOG_OK("ClassDescriptor: 0x" + ToHex(instanceOffsets.ClassDescriptor));
                LOG_OK("ClassName:     0x" + ToHex(instanceOffsets.ClassName));
            }
            else {
                LOG_ERR("instance offset discovery failed (nooooooooooo :( )");
            }
        }
        else {
            LOG_ERR("datamodel or just instance is not available or trying while game loading, skipping stage");
        }

        LOG_INFO("phase 5: scritp stage");
        ScriptOffsets scriptOffsets;

        if (dataModelObj != 0 && instanceOffsets.Valid) {
            scriptOffsets = FindScriptOffsets(hProc, dataModelObj, instanceOffsets);
            if (scriptOffsets.Valid) {
                LOG_OK("Script offsets discovered successfully");
                LOG_OK("  ModuleScript Bytecode: 0x" + ToHex(scriptOffsets.ModuleScriptBytecode));
                LOG_OK("  ModuleScript Hash:     0x" + ToHex(scriptOffsets.ModuleScriptHash));
                LOG_OK("  LocalScript Bytecode:  0x" + ToHex(scriptOffsets.LocalScriptBytecode));
                LOG_OK("  LocalScript Hash:      0x" + ToHex(scriptOffsets.LocalScriptHash));
                LOG_OK("  ByteCode Pointer:      0x" + ToHex(scriptOffsets.ByteCodePointer));
                LOG_OK("  ByteCode Size:         0x" + ToHex(scriptOffsets.ByteCodeSize));
            }
            else {
                LOG_ERR("script stage important is bullnotfounded");
            }
        }
        else {
            LOG_WARN("datamodel or just instance is not available or trying while game loading, skipping stage");
        }

        LOG_INFO("Phase 6: DataModel");
        DataModelOffsets dataModelOffsets;

        if (dataModelObj != 0 && instanceOffsets.Valid) {
            dataModelOffsets = FindDataModelOffsets(hProc, dataModelObj, instanceOffsets, rdataBuf, dataBuf, *pe);
            if (dataModelOffsets.Valid) {
                LOG_OK("DataModel properties discovered successfully");
                if (dataModelOffsets.GameLoaded)    LOG_OK("  GameLoaded: 0x" + ToHex(dataModelOffsets.GameLoaded));
                if (dataModelOffsets.JobId)         LOG_OK("  JobId:      0x" + ToHex(dataModelOffsets.JobId));
                if (dataModelOffsets.ServerIP)      LOG_OK("  ServerIP:   0x" + ToHex(dataModelOffsets.ServerIP));
            }
            else {
                LOG_ERR("DataModel properties discovery failed");
            }
        }
        else {
            LOG_WARN("datamodel or just instance is not available or trying while game loading, skipping stage");
        }

        LOG_INFO("Phase 7: humanoid stage");
        HumanoidOffsets humanoidOffsets;

        if (dataModelObj != 0 && instanceOffsets.Valid) {
            humanoidOffsets = FindHumanoidOffsets(hProc, dataModelObj, instanceOffsets);
            if (humanoidOffsets.Valid) {
                LOG_OK("Humanoid offsets discovered successfully");
                LOG_OK("  Health:               0x" + ToHex(humanoidOffsets.Health));
                LOG_OK("  MaxHealth:            0x" + ToHex(humanoidOffsets.MaxHealth));
                LOG_OK("  WalkSpeed:            0x" + ToHex(humanoidOffsets.WalkSpeed));
                LOG_OK("  JumpPower:            0x" + ToHex(humanoidOffsets.JumpPower));
                LOG_OK("  JumpHeight:           0x" + ToHex(humanoidOffsets.JumpHeight));
                LOG_OK("  HipHeight:            0x" + ToHex(humanoidOffsets.HipHeight));
                LOG_OK("  MaxSlopeAngle:        0x" + ToHex(humanoidOffsets.MaxSlopeAngle));
                LOG_OK("  WalkTimer:            0x" + ToHex(humanoidOffsets.WalkTimer));
                LOG_OK("  HealthDisplayDistance: 0x" + ToHex(humanoidOffsets.HealthDisplayDistance));
                LOG_OK("  AutoJumpEnabled:      0x" + ToHex(humanoidOffsets.AutoJumpEnabled));
                LOG_OK("  AutoRotate:           0x" + ToHex(humanoidOffsets.AutoRotate));
                LOG_OK("  Sit:                  0x" + ToHex(humanoidOffsets.Sit));
                LOG_OK("  BreakJointsOnDeath:   0x" + ToHex(humanoidOffsets.BreakJointsOnDeath));
                LOG_OK("  NameOcclusion:        0x" + ToHex(humanoidOffsets.NameOcclusion));
                LOG_OK("  PlatformStand:        0x" + ToHex(humanoidOffsets.PlatformStand));
                LOG_OK("  RequiresNeck:         0x" + ToHex(humanoidOffsets.RequiresNeck));
                LOG_OK("  UseJumpPower:         0x" + ToHex(humanoidOffsets.UseJumpPower));
                LOG_OK("  RigType:              0x" + ToHex(humanoidOffsets.RigType));
                LOG_OK("  HumanoidState:        0x" + ToHex(humanoidOffsets.HumanoidState));
                LOG_OK("  CameraOffset:         0x" + ToHex(humanoidOffsets.CameraOffset));
                LOG_OK("  MoveDirection:        0x" + ToHex(humanoidOffsets.MoveDirection));
                LOG_OK("  HumanoidRootPart:     0x" + ToHex(humanoidOffsets.HumanoidRootPart));
                LOG_OK("  SeatPart:             0x" + ToHex(humanoidOffsets.SeatPart));
                LOG_OK("  DisplayName:          0x" + ToHex(humanoidOffsets.DisplayName));
            }
        }
        else {
            LOG_WARN("datamodel or just instance is not available or trying while game loading, skipping stage");
        }

        LOG_INFO("Phase 8: workspace stage");
        WorkspaceOffsets workspaceOffsets;

        if (instanceOffsets.Valid && instanceOffsets.WorkspacePtr != 0) {
            workspaceOffsets = FindWorkspaceOffsets(hProc, instanceOffsets.WorkspacePtr, instanceOffsets);
            if (workspaceOffsets.Valid) {
                LOG_OK("Workspace offsets discovered successfully");
                LOG_OK("  CurrentCamera:       0x" + ToHex(workspaceOffsets.CurrentCamera));
                LOG_OK("  World:               0x" + ToHex(workspaceOffsets.World));
                LOG_OK("  DistributedGameTime: 0x" + ToHex(workspaceOffsets.DistributedGameTime));
            }
        }
        else {
            LOG_WARN("datamodel or just instance is not available or trying while game loading, skipping stage");
        }
        GenerateCombinedHeader("offsetsandfflags.h", taskSchedulerRVA, fields, fakeDataModelRVA,
            fakeToRealOffset, jobNameOffset, maxFpsOffset, flags,
            fflagOffsets.value_or(FFlagOffsets{}), modBase, instanceOffsets,
            scriptOffsets, dataModelOffsets, humanoidOffsets, workspaceOffsets);

        LOG_OK("done.");
        CloseHandle(hProc);
        std::cout << "Press any key to exit...\n";
        _getch();
        return 0;
    }   // closes the else block
}       // closes main()